Version: 5.4.2
config:
  customParsers: |
    [PARSER]
      Name docker
      Format json_lines
      Time_Keep Off
      Time_Key time
      Time_Format %Y-%m-%dT%H:%M:%S.%L
  filters: |
    [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Merge_Log_Key log_processed
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On

    [FILTER]
      Name    lua
      Match   kube.*
      script  /dedot-lua/dedot.lua
      call    dedot
  inputs: |
    [INPUT]
      Name tail
      Path /var/log/containers/*.log
      multiline.parser docker, cri
      Tag kube.*
      Mem_Buf_Limit ${fluent_bit_mem_buf}
      Skip_Long_Lines On

    [INPUT]
      Name systemd
      Tag host.*
      Systemd_Filter _SYSTEMD_UNIT=kubelet.service
      Read_From_Tail On
  outputs: |
    [OUTPUT]
      Name es
      Match kube.*_${fluent_bit_output_namespace}_*
      Host ${fluent_bit_output_elastic}
      Logstash_Format On
      Logstash_Prefix log-default
      Replace_Dots    On
      Retry_Limit False
  service: |
    [SERVICE]
      Flush 1
      Daemon Off
      Log_Level ${fluent_bit_log_level}
      Parsers_File parsers.conf
      Parsers_File custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port 2020
env:
- name: AWS_ACCESS_KEY_ID
  value: XXXX
- name: AWS_SECRET_ACCESS_KEY
  value: XXX
- name: AWS_DEFAULT_REGION
  value: eu-central-1
extraVolumeMounts:
- mountPath: /dedot-lua
  name: dedot-lua
extraVolumes:
- configMap:
    name: fluentbit-dedot-lua
  name: dedot-lua
podLabels:
  clusterName: one-q1l1l
  customer: AccountID
  environment: Prod
  region: eu-central-1
serviceMonitor:
  enabled: true
  interval: 10s
  namespace: default
  scrapeTimeout: 10s
  selector:
    release: prometheus
